name: "Auto-merge Dependabot PRs if Vercel build and tests pass"

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  wait-for-vercel-build:
    name: "Wait for Vercel build to complete"
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    outputs:
      build-status: ${{ steps.wait-for-build.outputs.conclusion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Wait for Vercel deployment
        id: wait-for-build
        uses: fountainhead/action-wait-for-check@5a908a24814494009c4bb27c242ea38c93c593be # 1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Vercel"
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 600
          intervalSeconds: 10

  approve-and-merge-pr:
    name: "Approve and merge Dependabot PR"
    runs-on: ubuntu-latest
    needs: wait-for-vercel-build
    if: ${{ github.actor == 'dependabot[bot]' && needs.wait-for-vercel-build.outputs.build-status == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Log changes to version"
        run: echo "Version going from ${{ steps.metadata.outputs.previous-version }}, to ${{ steps.metadata.outputs.new-version }}"

      - name: "Approve the PR"
        run: gh pr review --approve "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Merge the PR"
        run: gh pr merge --squash "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
